# Generated by Django 5.2.1 on 2025-05-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('original_url', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('CLEARBIT', 'Clearbit'), ('HTML_PARSER', 'HTML parser')], max_length=25)),
                ('version', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.websiteurl')),
            ],
        ),
    ]
