# Generated by Django 5.2.1 on 2025-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logosfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='mage_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
