# Generated by Django 5.2.1 on 2025-05-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logosfinder', '0002_logo_mage_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='mage_base64',
            new_name='image_base64',
        ),
    ]
