# Generated by Django 5.2.1 on 2025-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logosfinder', '0003_rename_mage_base64_logo_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
